import React, { useEffect } from 'react';

interface SEOProps {
  title: string;
  description: string;
  keywords: string[];
  ogImage?: string;
  appId?: string;
  appStoreUrl?: string;
  appCategory?: string;
  aggregateRating?: { ratingValue: string; ratingCount: string };
  faqs?: Array<{ question: string; answer: string }>;
  appNumericId?: string;
  screenshots?: string[];
  breadcrumbs?: Array<{ name: string; url: string }>;
  pageType?: 'guide' | 'compare';
  canonicalUrl?: string;
  datePublished?: string;
  comparisonTable?: Array<{ feature: string; app: string; competitor: string }>;
}

const BASE = 'https://briefly.live';

const SEOBox: React.FC<SEOProps> = ({
  title, description, keywords, ogImage, appId, appStoreUrl, appCategory,
  aggregateRating, faqs, appNumericId, screenshots, breadcrumbs, pageType, canonicalUrl, datePublished, comparisonTable,
}) => {
  useEffect(() => {
    document.title = title;

    const setMetaName = (name: string, content: string) => {
      let el = document.querySelector(`meta[name="${name}"]`);
      if (!el) { el = document.createElement('meta'); el.setAttribute('name', name); document.head.appendChild(el); }
      el.setAttribute('content', content);
    };

    const setMetaProp = (property: string, content: string) => {
      let el = document.querySelector(`meta[property="${property}"]`);
      if (!el) { el = document.createElement('meta'); el.setAttribute('property', property); document.head.appendChild(el); }
      el.setAttribute('content', content);
    };

    const resolvedCanonical = canonicalUrl || `${BASE}/${appId || ''}`;
    // Per-app social image (generated by scripts/images.mjs → /og/<id>.png).
    // Falls back to the generic image for the home page (no appId).
    const image = ogImage || (appId ? `${BASE}/og/${appId}.png` : `${BASE}/og-image.png`);
    const appName = title.split('|')[0].trim();

    // Basic
    setMetaName('description', description);
    setMetaName('keywords', keywords.join(', '));
    setMetaName('robots', 'index, follow');

    // Open Graph
    setMetaProp('og:title', title);
    setMetaProp('og:description', description);
    setMetaProp('og:type', pageType ? 'article' : 'website');
    setMetaProp('og:url', resolvedCanonical);
    setMetaProp('og:image', image);
    setMetaProp('og:image:width', '1200');
    setMetaProp('og:image:height', '630');
    setMetaProp('og:locale', 'en_US');
    setMetaProp('og:site_name', 'Briefly.live');

    if (pageType && datePublished) {
      setMetaProp('article:published_time', datePublished);
      setMetaProp('article:author', BASE);
    }

    // Twitter Cards
    setMetaName('twitter:card', 'summary_large_image');
    setMetaName('twitter:title', title);
    setMetaName('twitter:description', description);
    setMetaName('twitter:image', image);
    setMetaName('twitter:creator', '@shwiinn');

    if (appId && appNumericId) {
      setMetaName('apple-itunes-app', `app-id=${appNumericId}, app-argument=${BASE}/${appId}`);
      setMetaProp('al:ios:app_name', appName);
      setMetaProp('al:ios:app_store_id', appNumericId);
      setMetaProp('al:ios:url', `${appId}://home`);
      setMetaName('twitter:app:name:iphone', appName);
      setMetaName('twitter:app:id:iphone', appNumericId);
    }

    // Canonical
    let canonical = document.querySelector('link[rel="canonical"]');
    if (!canonical) { canonical = document.createElement('link'); canonical.setAttribute('rel', 'canonical'); document.head.appendChild(canonical); }
    canonical.setAttribute('href', resolvedCanonical);

    // Primary JSON-LD
    let script = document.querySelector('script[data-seo="primary"]') as HTMLScriptElement | null;
    if (!script) {
      script = document.createElement('script');
      script.setAttribute('type', 'application/ld+json');
      script.setAttribute('data-seo', 'primary');
      document.head.appendChild(script);
    }

    const schema = appId ? {
      '@context': 'https://schema.org',
      '@type': 'MobileApplication',
      name: appName,
      description,
      applicationCategory: appCategory || 'HealthApplication',
      operatingSystem: 'iOS',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      url: appStoreUrl || resolvedCanonical,
      author: { '@type': 'Person', name: 'Ashwin Anbazhagan', url: BASE },
      ...(aggregateRating && {
        aggregateRating: {
          '@type': 'AggregateRating',
          ratingValue: aggregateRating.ratingValue,
          ratingCount: aggregateRating.ratingCount,
        },
      }),
      ...(screenshots?.length && {
        screenshot: screenshots.map(s => `${BASE}${s}`),
      }),
    } : {
      '@context': 'https://schema.org',
      '@type': 'Organization',
      name: 'Briefly',
      url: BASE,
      logo: `${BASE}/apple-touch-icon.png`,
      sameAs: ['https://twitter.com/shwiinn'],
      founder: { '@type': 'Person', name: 'Ashwin Anbazhagan' },
    };

    script.textContent = JSON.stringify(schema);

    // BreadcrumbList JSON-LD
    let breadcrumbScript = document.querySelector('script[data-seo="breadcrumb"]') as HTMLScriptElement | null;
    if (breadcrumbs && breadcrumbs.length > 0) {
      if (!breadcrumbScript) {
        breadcrumbScript = document.createElement('script');
        breadcrumbScript.setAttribute('type', 'application/ld+json');
        breadcrumbScript.setAttribute('data-seo', 'breadcrumb');
        document.head.appendChild(breadcrumbScript);
      }
      breadcrumbScript.textContent = JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'BreadcrumbList',
        itemListElement: breadcrumbs.map((b, i) => ({
          '@type': 'ListItem',
          position: i + 1,
          name: b.name,
          item: b.url,
        })),
      });
    } else if (breadcrumbScript) {
      breadcrumbScript.remove();
    }

    // Article JSON-LD (for pSEO guide pages)
    let articleScript = document.querySelector('script[data-seo="article"]') as HTMLScriptElement | null;
    if (pageType === 'guide') {
      if (!articleScript) {
        articleScript = document.createElement('script');
        articleScript.setAttribute('type', 'application/ld+json');
        articleScript.setAttribute('data-seo', 'article');
        document.head.appendChild(articleScript);
      }
      articleScript.textContent = JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'Article',
        headline: title,
        description,
        author: {
          '@type': 'Person',
          name: 'Ashwin Anbazhagan',
          url: BASE,
        },
        datePublished: datePublished || '2025-01-01',
        dateModified: new Date().toISOString().split('T')[0],
        image: ogImage || `${BASE}/og-image.png`,
      });
    } else if (articleScript) {
      articleScript.remove();
    }

    // FAQPage JSON-LD
    let faqScript = document.querySelector('script[data-seo="faq"]') as HTMLScriptElement | null;
    if (faqs && faqs.length > 0) {
      if (!faqScript) {
        faqScript = document.createElement('script');
        faqScript.setAttribute('type', 'application/ld+json');
        faqScript.setAttribute('data-seo', 'faq');
        document.head.appendChild(faqScript);
      }
      faqScript.textContent = JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'FAQPage',
        mainEntity: faqs.map(f => ({
          '@type': 'Question',
          name: f.question,
          acceptedAnswer: { '@type': 'Answer', text: f.answer },
        })),
      });
    } else if (faqScript) {
      faqScript.remove();
    }

    // ComparisonTable JSON-LD (for compare pages)
    let tableScript = document.querySelector('script[data-seo="comparison"]') as HTMLScriptElement | null;
    if (comparisonTable && comparisonTable.length > 0 && pageType === 'compare') {
      if (!tableScript) {
        tableScript = document.createElement('script');
        tableScript.setAttribute('type', 'application/ld+json');
        tableScript.setAttribute('data-seo', 'comparison');
        document.head.appendChild(tableScript);
      }
      tableScript.textContent = JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'ItemList',
        name: title,
        itemListElement: comparisonTable.map((row, i) => ({
          '@type': 'ListItem',
          position: i + 1,
          name: row.feature,
          description: `${row.app} vs ${row.competitor}`,
        })),
      });
    } else if (tableScript) {
      tableScript.remove();
    }
  }, [title, description, keywords, ogImage, appId, appStoreUrl, appCategory, aggregateRating, faqs, appNumericId, screenshots, breadcrumbs, pageType, canonicalUrl, datePublished, comparisonTable]);

  return null;
};

export default SEOBox;
