/**
 * Post-build SSR prerender: builds a server bundle from entry-server.tsx,
 * renders each route with renderToString, and writes complete HTML files
 * (full body + injected head meta) to dist/ so crawlers see real content.
 *
 * SINGLE SOURCE OF TRUTH: the app list and pSEO pages are imported directly
 * from the built SSR bundle (which re-exports src/config/apps.ts and
 * src/config/pseo.ts). Never re-declare them here — that caused the catalog
 * to drift out of sync with what the SPA actually renders.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const DIST = path.join(ROOT, 'dist');
const DIST_SSR = path.join(ROOT, 'dist-ssr');
const BASE = 'https://briefly.live';
const BUILD_DATE = new Date().toISOString().split('T')[0];

const homeSeo = {
  title: 'Ashwin Anbazhagan | iOS App Developer & Founder',
  description: 'Indie iOS apps for gut health, studying, morning journaling and fandom. Each one solves one specific problem, precisely.',
  keywords: ['Ashwin Anbazhagan', 'iOS App Developer', 'Indie App Maker', 'SaaS Founder', 'App Developer India'],
};

// Per-app social share image. Generated by scripts/images.mjs → public/og/<id>.png.
const ogFor = (appId) => (appId ? `${BASE}/og/${appId}.png` : `${BASE}/og-image.png`);

// ─── Helpers ─────────────────────────────────────────────────────────────────
function buildHead({ title, description, keywords, canonical, appStoreUrl, downloadUrl, seoApplicationCategory, appName, appNumericId, appId, aggregateRating, screenshots, faqs, breadcrumbs, pageType, datePublished, image }) {
  const kw = keywords.join(', ');
  const ogImage = image || ogFor(appId);

  const appSchema = appName ? JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'MobileApplication',
    name: appName,
    description,
    applicationCategory: seoApplicationCategory || 'HealthApplication',
    operatingSystem: 'iOS 15.0+',
    downloadUrl: downloadUrl || appStoreUrl,
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    url: appStoreUrl || canonical,
    author: { '@type': 'Person', name: 'Ashwin Anbazhagan', url: BASE },
    ...(aggregateRating && {
      aggregateRating: {
        '@type': 'AggregateRating',
        ratingValue: aggregateRating.ratingValue,
        ratingCount: aggregateRating.ratingCount,
      },
    }),
    ...(screenshots?.length && {
      screenshot: screenshots.map(s => `${BASE}${s}`),
    }),
  }) : JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'Organization',
    name: 'Briefly',
    url: BASE,
    logo: `${BASE}/apple-touch-icon.png`,
    sameAs: ['https://twitter.com/shwiinn'],
    founder: { '@type': 'Person', name: 'Ashwin Anbazhagan' },
  });

  const breadcrumbSchema = (breadcrumbs && breadcrumbs.length > 0) ? `
    <script type="application/ld+json">${JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: breadcrumbs.map((b, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: b.name,
        item: b.url,
      })),
    })}</script>` : '';

  const faqSchema = (faqs && faqs.length > 0) ? `
    <script type="application/ld+json">${JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: faqs.map(f => ({
        '@type': 'Question',
        name: f.question,
        acceptedAnswer: { '@type': 'Answer', text: f.answer },
      })),
    })}</script>` : '';

  const articleSchema = (pageType === 'guide') ? `
    <script type="application/ld+json">${JSON.stringify({
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: title,
      description,
      author: { '@type': 'Person', name: 'Ashwin Anbazhagan', url: BASE },
      datePublished: datePublished || '2025-01-01',
      dateModified: BUILD_DATE,
      image: ogImage,
    })}</script>` : '';

  const appMetaTags = (appId && appNumericId) ? `
    <meta name="apple-itunes-app" content="app-id=${appNumericId}, app-argument=${BASE}/${appId}">
    <meta property="al:ios:app_name" content="${appName}">
    <meta property="al:ios:app_store_id" content="${appNumericId}">
    <meta property="al:ios:url" content="${appId}://home">
    <meta name="twitter:app:name:iphone" content="${appName}">
    <meta name="twitter:app:id:iphone" content="${appNumericId}">` : '';

  // Per-app favicon (#23 brand recognition); generic Briefly mark on the home page.
  const favicon = appId ? `${BASE}/${appId}.png` : `${BASE}/favicon.png`;

  return `
    <title>${title}</title>
    <meta name="description" content="${description}">
    <meta name="keywords" content="${kw}">
    <meta name="robots" content="index, follow">
    <link rel="icon" type="image/png" href="${favicon}">
    <link rel="apple-touch-icon" href="${favicon}">
    <link rel="canonical" href="${canonical}">
    <meta property="og:title" content="${title}">
    <meta property="og:description" content="${description}">
    <meta property="og:type" content="${pageType ? 'article' : 'website'}">
    <meta property="og:url" content="${canonical}">
    <meta property="og:image" content="${ogImage}">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:locale" content="en_US">
    <meta property="og:site_name" content="Briefly.live">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="${title}">
    <meta name="twitter:description" content="${description}">
    <meta name="twitter:image" content="${ogImage}">
    <meta name="twitter:creator" content="@shwiinn">${appMetaTags}
    <script type="application/ld+json">${appSchema}</script>${breadcrumbSchema}${faqSchema}${articleSchema}`.trim();
}

function writeRoute(templateHtml, routePath, headContent, bodyHtml) {
  const dir = path.join(DIST, ...routePath.split('/').filter(Boolean));
  fs.mkdirSync(dir, { recursive: true });

  let html = templateHtml;
  html = html.replace('</head>', `  ${headContent}\n  </head>`);
  html = html.replace('<div id="root"></div>', `<div id="root">${bodyHtml}</div>`);

  fs.writeFileSync(path.join(dir, 'index.html'), html);
  console.log(`  ✓ ${routePath || '/'}`);
}

// ─── Build SSR bundle ─────────────────────────────────────────────────────────
console.log('\nBuilding SSR bundle...');
execSync(
  'npx vite build --ssr src/entry-server.tsx --outDir dist-ssr --emptyOutDir',
  { stdio: 'inherit', cwd: ROOT }
);

// ─── Load render function + canonical data (single source of truth) ───────────
const { render, apps, pseoPages: allPseoPages } = await import(path.join(DIST_SSR, 'entry-server.js'));

// Guard against stale pSEO entries whose app was removed from apps.ts (e.g. a
// discontinued app) — never prerender or sitemap a page whose app doesn't exist.
const pseoPages = allPseoPages.filter(page => apps.some(a => a.id === page.appId));

// ─── Read client template ─────────────────────────────────────────────────────
const templateHtml = fs.readFileSync(path.join(DIST, 'index.html'), 'utf-8')
  // Strip the template's static favicon links — buildHead injects per-app ones.
  .replace(/\s*<link rel="icon"[^>]*>/g, '')
  .replace(/\s*<link rel="apple-touch-icon"[^>]*>/g, '');

// ─── Generate routes ──────────────────────────────────────────────────────────
console.log('\nPrerendering routes...');

// Home
{
  const bodyHtml = render('/');
  const headContent = buildHead({
    title: homeSeo.title,
    description: homeSeo.description,
    keywords: homeSeo.keywords,
    canonical: BASE,
    appName: null,
    appId: null,
    appNumericId: null,
    aggregateRating: null,
    screenshots: null,
    faqs: null,
  });
  let html = templateHtml;
  html = html.replace('</head>', `  ${headContent}\n  </head>`);
  html = html.replace('<div id="root"></div>', `<div id="root">${bodyHtml}</div>`);
  fs.writeFileSync(path.join(DIST, 'index.html'), html);
  console.log('  ✓ /');
}

// App routes
for (const app of apps) {
  const sections = ['', 'privacy-policy', 'terms-of-service', 'support'];
  for (const sec of sections) {
    const routePath = sec ? `/${app.id}/${sec}` : `/${app.id}`;
    const canonical = `${BASE}${routePath}`;
    const title = sec
      ? `${sec.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase())} | ${app.name}`
      : app.seo.title;

    const bodyHtml = render(routePath);
    const headContent = buildHead({
      title,
      description: app.seo.description,
      keywords: app.seo.keywords,
      canonical,
      appStoreUrl: app.appStoreUrl,
      downloadUrl: sec ? null : app.downloadUrl,
      seoApplicationCategory: sec ? null : app.seoApplicationCategory,
      appName: app.name,
      appNumericId: sec ? null : app.appNumericId,
      appId: app.id,
      aggregateRating: sec ? null : app.aggregateRating,
      screenshots: sec ? null : app.marketing?.screenshots,
      faqs: sec ? null : app.marketing?.faqs,
    });

    writeRoute(templateHtml, routePath, headContent, bodyHtml);
  }
}

// pSEO routes
for (const page of pseoPages) {
  const routePath = `/${page.appId}/${page.type}/${page.slug}`;
  const canonical = `${BASE}${routePath}`;
  const app = apps.find(a => a.id === page.appId);

  const bodyHtml = render(routePath);
  const breadcrumbs = [
    { name: 'Home', url: `${BASE}/` },
    { name: app?.name || '', url: `${BASE}/${page.appId}` },
    { name: page.h1 || page.title, url: canonical },
  ];
  const headContent = buildHead({
    title: page.title,
    description: page.metaDescription,
    keywords: app ? app.seo.keywords : [],
    canonical,
    appStoreUrl: app?.appStoreUrl,
    seoApplicationCategory: app?.seoApplicationCategory,
    appName: app?.name,
    appNumericId: app?.appNumericId,
    appId: page.appId,
    aggregateRating: null,
    screenshots: null,
    faqs: page.faqs,
    breadcrumbs,
    pageType: page.type,
    datePublished: page.datePublished,
  });

  writeRoute(templateHtml, routePath, headContent, bodyHtml);
}

// ─── Generate sitemap.xml ─────────────────────────────────────────────────────
const sitemapEntries = [];

sitemapEntries.push({ loc: BASE, lastmod: BUILD_DATE, priority: 1.0, changefreq: 'monthly' });

for (const app of apps) {
  sitemapEntries.push({ loc: `${BASE}/${app.id}`, lastmod: BUILD_DATE, priority: 0.9, changefreq: 'monthly' });
  for (const sec of ['privacy-policy', 'terms-of-service', 'support']) {
    sitemapEntries.push({ loc: `${BASE}/${app.id}/${sec}`, lastmod: BUILD_DATE, priority: 0.3, changefreq: 'yearly' });
  }
}

for (const page of pseoPages) {
  sitemapEntries.push({
    loc: `${BASE}/${page.appId}/${page.type}/${page.slug}`,
    lastmod: page.datePublished || BUILD_DATE,
    priority: 0.8,
    changefreq: 'monthly',
  });
}

const sitemapXml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${sitemapEntries.map(entry => `  <url>
    <loc>${entry.loc}</loc>
    <lastmod>${entry.lastmod}</lastmod>
    <changefreq>${entry.changefreq}</changefreq>
    <priority>${entry.priority}</priority>
  </url>`).join('\n')}
</urlset>`;

fs.writeFileSync(path.join(DIST, 'sitemap.xml'), sitemapXml);

console.log(`\nDone. ${sitemapEntries.length} URLs in sitemap. All routes pre-rendered with full HTML.\n`);
